services:
  express-app:
    image: tranche100/cicdtest:latest
    ports:
    - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=40 # Poll every 40 seconds
      -  WATCHTOWER_LABEL_ENABLE=true
      -  DOCKER_API_VERSION=1.44 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower